name:                dnote
version:             0.1.0.0
github:              "sebaci/dnote"
license:             BSD3
author:              "Sebastian Cielemęcki"
maintainer:          "sc.gman@gmail.com"
copyright:           "2022 Sebastian Cielemęcki"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dnote#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp

library:
  source-dirs: src

executables:
  dnote-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - dnote

tests:
  dnote-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - dnote
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
